[application]
name = "webtemplate"

[bundle]
identifier = "com.dioxuslabs"
publisher = "Youknowwho55"
icon = ["assets/icon.png"]


[web.app]

# HTML title tag content
title = "mortgage"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []




